### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by mgoral** [robin92/tw4a#74]
Well, I know that @rosshadden is working (or not?) on sync with taskserver, but nevertheless I think that it'd be a nice option to be able to actually export taskwarrior's data (you know, all these things that are normally stored in `~/.task`).

Problem is that when removing an app, Android removes its storage, so after uninstalling and installing it back we loose all our precious tasks. Which is bad in my opinion. Probably not that bad if you have a remote copy of them, but still bad.

Is packing these files (to some kind of `zip` probably) and storing them on sdcard is possible at all? Or maybe some other way to export the data?

**Comment by robin92** [comment]
Indeed, this is possible. I must check whether ~~Carbon~~ Helium can backup this information but without root access I hardly think so.

**Comment by robin92** [comment]
The idea is to create a ZIP file with taskwarrior's data inside application cache and then share it using `ContentProvider`. I need to research when the cache can be cleared in order not to remove a currently sharing file.

**Comment by mgoral** [comment]
That's exactly what I meant (I think ;))
