### ISSUE TITLE
Low buildToolsVersion

### ISSUE THREAD

**Issue by mgoral** [robin92/tw4a#79]
I'm leaving this issue as a low priority reference, so it's not forgotten.

As far as I understand version 21 of buildTools is set because Travis has installed only this version, at least according to their [docs](https://docs.travis-ci.com/user/languages/android#Pre-installed-components). But it seems that [other projects](https://github.com/zeapo/Android-Password-Store) successfully use version 23.0.2, so maybe it's worth a shot? Are there any other problems (like with emulator)?

**Comment by robin92** [comment]
No problems with emulator or other stuff, only travis. Since other projects use newer build tools I will try updating and see what happens.

Btw, your link missed a dot in domain.
